# Generated by Django 3.0.5 on 2020-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=0, verbose_name=range(1, 10)),
        ),
    ]
